[package]
name = "test_1"
version = "0.1.0"
authors = ["Sergio Ornaque"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
